var marggin = 50,
    my_tank={},
    all_spite=[],
    my_wiper={},
    velosity = 1,
    velosity_weap = 2,
    scale =1,
    length=50,
    pl_length=35,
    marggin=100,
    mob = 15,
    explosion,
    numberOfrow= Math.floor((window.innerWidth-marggin*2)/length),
    numberOfcol= Math.floor((window.innerHeight-marggin*2)/length)
